version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: spa_db
    restart: always
    environment:
      POSTGRES_USER: zen
      POSTGRES_PASSWORD: zenpass
      POSTGRES_DB: test_db
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
