type User {
  id: ID!
  username: String!
  email: String!
  role: String!
}

type Comment {
  id: ID!
  userId: String!
  text: String!
  filePath: String
  parentId: String
  createdAt: DateTime!
  user: User
  parent: Comment
}

"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

type Query {
  getComments: [Comment!]!
}

type Mutation {
  createComment(input: CreateCommentInput!): Boolean!
}

input CreateCommentInput {
  userId: String!
  text: String!
  homePage: String
  parentId: String
  filePath: String
}